# Generated by Django 2.2 on 2020-08-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobservice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobkeyword',
            name='keyword',
            field=models.TextField(),
        ),
    ]
