# Generated by Django 2.2 on 2020-08-18 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobservice', '0002_auto_20200812_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('job_url', models.URLField()),
                ('summary', models.TextField()),
                ('confirm', models.BooleanField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
