# Generated by Django 2.2 on 2020-04-17 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyservice', '0002_auto_20200411_0619'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordCityRel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyservice.City')),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyservice.Keyword')),
            ],
        ),
    ]
