# Generated by Django 2.2 on 2020-05-22 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyservice', '0003_keywordcityrel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
