# Generated by Django 2.2 on 2020-06-10 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyservice', '0005_auto_20200527_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='it_has_map',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='keyword',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
