# Generated by Django 2.2 on 2020-06-11 06:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyservice', '0006_auto_20200610_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq_no', models.IntegerField(default=0)),
                ('position', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=50)),
                ('date', models.DateField(default=datetime.date.today)),
                ('keyword_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='keyservice.Keyword')),
            ],
        ),
    ]
