# Generated by Django 3.1.5 on 2021-01-11 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('keyservice', '0008_auto_20201118_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapposition',
            name='keyword_id',
        ),
    ]
